name: Updater Build

on:
  push:
    branches: [main]

jobs:
  build-updater:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-14, ubuntu-latest, windows-latest]

    outputs:
      version: ${{ steps.get_version.outputs.version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 22.x

      - name: Install yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install

      - name: Build Electron app with obfuscation
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node build-script.js

      - name: Get version from package.json
        shell: bash
        id: get_version
        run: |
          version=$(jq -r .version ./package.json)
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: electron-build-${{ matrix.os }}
          path: ./dist/

  create-release:
    needs: build-updater
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./dist

      - name: List downloaded files (debug)
        run: ls -R ./dist

      - name: Find files to upload
        id: filtered_files
        run: |
          files=$(find ./dist -type f \( \
            -name "Valkream-Updater-linux-x86_64.AppImage" -o \
            -name "Valkream-Updater-mac-universal.dmg" -o \
            -name "Valkream-Updater-mac-universal.dmg.blockmap" -o \
            -name "Valkream-Updater-mac-universal.zip" -o \
            -name "Valkream-Updater-win-x64.exe" -o \
            -name "Valkream-Updater-win-x64.exe.blockmap" -o \
            -name "Valkream-Updater.exe" \
          \))

          echo "Matched files:"
          echo "$files"

          # Format GitHub Actions : écrire dans le fichier de sortie
          echo "files=$(echo "$files" | paste -sd "," -)" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.build-updater.outputs.version }}
          name: release ${{ needs.build-updater.outputs.version }}
          draft: false
          prerelease: false
          fail_on_unmatched_files: true
          overwrite: true
          files: ${{ steps.filtered_files.outputs.files }}
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
